apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: metrics-server
    namespace: argocd
    finalizers:
        - resources-finalizer.argocd.argoproj.io
spec:
    destination:
        namespace: kube-system
        server: {{ .Values.spec.destination.server }}
    project: default
    source:
        chart: metrics-server
        helm:
            values: |
                args:
                    - '--kubelet-insecure-tls'
        repoURL: https://kubernetes-sigs.github.io/metrics-server/
        targetRevision: 3.7.0
    syncPolicy:
        automated:
            prune: true
            selfHeal: true