apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - metrics-server.yaml
  - sealed-secrets.yaml
  - ingress.yaml
  - external-dns-ns.yaml
  - external-dns-cloudflare-secret-sealed.yaml
  # - external-dns.yaml
  # - guestbook.yaml
